apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-forward-starter-deployment
  labels:
    app: spring-forward-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-forward-starter
  template:
    metadata:
      labels:
        app: spring-forward-starter
    spec:
      containers:
      - name: spring-forward-starter
        image: registry.ng.bluemix.net/elstarit/spring-forward-starter:latest
        ports:
        - containerPort: 8089

---
kind: Service
apiVersion: v1
metadata:
  name: spring-forward-starter-deployment
spec:
  selector:
    app: spring-forward-starter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8089