server:
  port: 8085
  servlet:
    context-path: /spring-starter

logging:
  level:
    root: INFO
    org:
      springframework:
        security: ERROR

info:
  app:
    name: Spring Forward Starter
    version: 0.0.1-SNAPSHOT
    description: Spring Forward Starter

spring:
  application:
    name: Spring Forward Starter
  profiles:
      active: @activeProfile@

springfox:
  documentation:
    swagger:
      v2:
        path: "/v2/api-docs"

management:
  server:
    servlet:
      context-path: /actuator


---
spring:
  profiles: dev


---
spring:
  profiles: prod

---
